### PR TITLE
Add NodeType.ROUTER

### PR DESCRIPTION
**Pull request by parherman**

### CODE REVIEW

**Comment by sfalkman** [comment]
Let's continue the #10 discussion here.

I'm sorry to drag this out, but I'd like some more information about this. I can't reproduce the error you're having when nodes are being iterated. Can you provide an error output?

Could you please run this and post the output? I don't get any `NodeType.ROUTER` in my node list..
```python
with Ngenic(token="YOUR_API_TOKEN") as ngenic:
    for tune in ngenic.tunes():
        for node in tune.nodes():
            print("Type: %s\nMeasurements: %s\n----" %
                    (
                        node.get_type(),
                        list(m.get_type() for m in node.measurements())
                    )
            )
```

**Comment by parherman** [comment]
It would only show up if you have router connected to your tune. A router is a node that can be used to extend the range of other nodes

This is the original error, without the fix in #10:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ngenic/sensor.py", line 121, in async_setup_entry
    node_name = "Ngenic %s" % node.get_type().name.lower()
  File "/usr/local/lib/python3.8/site-packages/ngenicpy/models/node.py", line 26, in get_type
    return NodeType(self["type"])
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 4 is not a valid NodeType
```

**Comment by parherman** [comment]
And here is the relevant output from the script above, with the patch in this PR applied:

```
Type: NodeType.ROUTER
Measurements: []
```

Is has now Measurements, its just used to extend the node network!

**Comment by sfalkman** [comment]
Oooh, I didn't know that existed.. Is it called "router"? I can't find any product information, do you have a link?  
I'll get on this as soon as I can

**Comment by parherman** [comment]
Thanks!

I do not have anymore documentation unfortunately, but no more information then the type is exposed through the api I believe. No measurements or other information.

**Comment by sfalkman** [comment]
I've bumped the ngenicpy version and updated the hass component.

**Pull request merged**
